import type { Locale } from '../types/domain'

export const isLocale = (value: string | undefined): value is Locale =>
  value === 'en' || value === 'hi'

export const copy = {
  en: {
    brandSub: 'Parenting support',
    navHome: 'Home',
    navResources: 'Learning resources',
    navAbout: 'About',
    navContact: 'Contact',
    menu: 'Menu',
    closeMenu: 'Close menu',
    switchLanguageLabel: 'Switch to Hindi',
    heroEyebrow: 'Bilingual parenting support',
    heroTitle: 'Helping Indian immigrant families thrive in Australia',
    heroIntro:
      'Practical English and Hindi video lessons for parents navigating culture, family life and children’s wellbeing.',
    explore: 'Explore learning resources',
    aboutCta: 'About C-BEEMS',
    introductionTitle: 'Introduction video',
    introductionLoading: 'Loading the introduction video…',
    introductionError: 'The introduction video could not be loaded.',
    introductionUnavailable: 'The introduction video is available on the published site.',
    resourcesTitle: 'Learning resources',
    resourcesIntro: 'Start with any lesson, then continue at your own pace.',
    lesson: 'Lesson',
    videoLesson: 'English video',
    videoPlaceholder: 'This video is not currently available.',
    mediaStatus: 'Only the selected-language video is displayed.',
    emulatorLoading: 'Loading learning resources…',
    emulatorConnected: 'Learning resources loaded',
    emulatorError: 'Learning resources could not be refreshed. The saved resource list is shown.',
    retry: 'Retry',
    videoLoading: 'Loading the selected-language video…',
    videoError: 'The selected-language video could not be loaded.',
    backToResources: 'Back to resources',
    previous: 'Previous lesson',
    next: 'Next lesson',
    supportTitle: 'Need urgent support?',
    supportText:
      'C-BEEMS is not an emergency service. Contact us for general enquiries and support information.',
    getHelp: 'Get help',
    aboutTitle: 'About C-BEEMS',
    aboutText:
      'Our full project background, team, partner and funder information is coming soon.',
    reservedLabel: 'Content coming soon',
    contactTitle: 'Contact and get help',
    contactText:
      'For general enquiries, contact C-BEEMS using the phone number or email address below.',
    contactDetailsLabel: 'Contact details',
    formName: 'Name',
    formEmail: 'Email',
    formMessage: 'Message',
    formSubmit: 'Send message',
    formDisabled: 'Online form submissions are not currently available. Please use the contact details above.',
    privacyTitle: 'Privacy Policy',
    accessibilityTitle: 'Accessibility Statement',
    cookiePreferences: 'Cookie preferences',
    cookieTitle: 'Your privacy choices',
    cookieText: 'This site uses essential browser storage for your language and cookie preferences.',
    essential: 'Essential — always active',
    saveChoices: 'Save choices',
    socialLinksLabel: 'Social media links',
    notFoundTitle: 'Page not found',
    notFoundText: 'The page may have moved or the address may be incorrect.',
    returnHome: 'Return home',
    skipToContent: 'Skip to content',
    breadcrumbHome: 'Home',
  },
  hi: {
    brandSub: 'पालन-पोषण सहायता',
    navHome: 'मुखपृष्ठ',
    navResources: 'सीखने के संसाधन',
    navAbout: 'हमारे बारे में',
    navContact: 'संपर्क',
    menu: 'मेनू',
    closeMenu: 'मेनू बंद करें',
    switchLanguageLabel: 'Switch to English',
    heroEyebrow: 'द्विभाषी पालन-पोषण सहायता',
    heroTitle: 'ऑस्ट्रेलिया में भारतीय प्रवासी परिवारों के लिए सहायता',
    heroIntro:
      'संस्कृति, पारिवारिक जीवन और बच्चों के कल्याण के लिए अंग्रेज़ी और हिन्दी वीडियो पाठ।',
    explore: 'सीखने के संसाधन देखें',
    aboutCta: 'C-BEEMS के बारे में',
    introductionTitle: 'परिचय वीडियो',
    introductionLoading: 'परिचय वीडियो लोड हो रहा है…',
    introductionError: 'परिचय वीडियो लोड नहीं हो सका।',
    introductionUnavailable: 'परिचय वीडियो प्रकाशित वेबसाइट पर उपलब्ध है।',
    resourcesTitle: 'सीखने के संसाधन',
    resourcesIntro: 'किसी भी पाठ से शुरू करें और अपनी गति से आगे बढ़ें।',
    lesson: 'पाठ',
    videoLesson: 'हिन्दी वीडियो',
    videoPlaceholder: 'यह वीडियो अभी उपलब्ध नहीं है।',
    mediaStatus: 'केवल चुनी हुई भाषा का वीडियो दिखाया जाता है।',
    emulatorLoading: 'सीखने के संसाधन लोड हो रहे हैं…',
    emulatorConnected: 'सीखने के संसाधन लोड हो गए हैं',
    emulatorError: 'सीखने के संसाधन रीफ़्रेश नहीं हो सके। सहेजी गई सूची दिखाई जा रही है।',
    retry: 'फिर प्रयास करें',
    videoLoading: 'चुनी हुई भाषा का वीडियो लोड हो रहा है…',
    videoError: 'चुनी हुई भाषा का वीडियो लोड नहीं हो सका।',
    backToResources: 'संसाधनों पर वापस जाएँ',
    previous: 'पिछला पाठ',
    next: 'अगला पाठ',
    supportTitle: 'तत्काल सहायता चाहिए?',
    supportText:
      'C-BEEMS आपात सेवा नहीं है। सामान्य पूछताछ और सहायता जानकारी के लिए हमसे संपर्क करें।',
    getHelp: 'सहायता प्राप्त करें',
    aboutTitle: 'C-BEEMS के बारे में',
    aboutText:
      'हमारी परियोजना, टीम, भागीदार और वित्तपोषक की पूरी जानकारी जल्द उपलब्ध होगी।',
    reservedLabel: 'सामग्री जल्द आ रही है',
    contactTitle: 'संपर्क और सहायता',
    contactText:
      'सामान्य पूछताछ के लिए नीचे दिए फ़ोन नंबर या ईमेल पते से C-BEEMS से संपर्क करें।',
    contactDetailsLabel: 'संपर्क विवरण',
    formName: 'नाम',
    formEmail: 'ईमेल',
    formMessage: 'संदेश',
    formSubmit: 'संदेश भेजें',
    formDisabled: 'ऑनलाइन फ़ॉर्म अभी उपलब्ध नहीं है। कृपया ऊपर दिए संपर्क विवरण का उपयोग करें।',
    privacyTitle: 'गोपनीयता नीति',
    accessibilityTitle: 'सुलभता वक्तव्य',
    cookiePreferences: 'कुकी प्राथमिकताएँ',
    cookieTitle: 'आपकी गोपनीयता पसंद',
    cookieText: 'यह साइट आपकी भाषा और कुकी पसंद सहेजने के लिए केवल आवश्यक ब्राउज़र स्टोरेज का उपयोग करती है।',
    essential: 'आवश्यक — हमेशा सक्रिय',
    saveChoices: 'पसंद सहेजें',
    socialLinksLabel: 'सोशल मीडिया लिंक',
    notFoundTitle: 'पृष्ठ नहीं मिला',
    notFoundText: 'यह पृष्ठ स्थानांतरित हो सकता है या पता गलत हो सकता है।',
    returnHome: 'मुखपृष्ठ पर जाएँ',
    skipToContent: 'मुख्य सामग्री पर जाएँ',
    breadcrumbHome: 'मुखपृष्ठ',
  },
} as const
