import type { Lesson, Locale } from './types/domain'

export type {
  Lesson,
  LessonCategory,
  Locale,
  LocaleProps,
  MediaReference,
  PrototypeLesson,
} from './types/domain'

export const supportedLocales: Locale[] = ['en', 'hi']

export const isLocale = (value: string | undefined): value is Locale =>
  value === 'en' || value === 'hi'

export const lessons: Lesson[] = [
  {
    slug: 'enculturation-and-acculturation',
    category: 'culture',
    title: {
      en: 'Enculturation & Acculturation',
      hi: 'संस्कृतिकरण और नई संस्कृति को अपनाना',
    },
  },
  {
    slug: 'four-ways-of-acculturation',
    category: 'culture',
    title: {
      en: 'Four Ways of Acculturation',
      hi: 'नई संस्कृति अपनाने के चार तरीके',
    },
  },
  {
    slug: 'children-adapt-faster',
    category: 'culture',
    title: {
      en: 'Children Adapt Faster',
      hi: 'बच्चे अधिक तेज़ी से अनुकूल होते हैं',
    },
  },
  {
    slug: 'lived-experiences',
    category: 'culture',
    title: {
      en: 'Lived Experiences',
      hi: 'जीवन के अनुभव',
    },
  },
  {
    slug: 'protective-parental-factors',
    category: 'parenting',
    title: {
      en: 'Protective Parental Factors',
      hi: 'माता-पिता के सुरक्षात्मक कारक',
    },
  },
  {
    slug: 'less-helpful-parenting-approaches',
    category: 'parenting',
    title: {
      en: 'Less Helpful Parenting Approaches',
      hi: 'कम सहायक पालन-पोषण के तरीके',
    },
  },
  {
    slug: 'mental-health-wellbeing-spectrum',
    category: 'wellbeing',
    title: {
      en: 'Mental Health Well-Being Spectrum',
      hi: 'मानसिक स्वास्थ्य और कल्याण का दायरा',
    },
  },
  {
    slug: 'immigrant-specific-mental-health-risk-factors',
    category: 'wellbeing',
    title: {
      en: 'Immigrant Specific Mental Health Risk Factors',
      hi: 'प्रवासी परिवारों के मानसिक स्वास्थ्य जोखिम',
    },
  },
]

export const copy = {
  en: {
    brandSub: 'Parenting support',
    navHome: 'Home',
    navResources: 'Learning resources',
    navAbout: 'About',
    navContact: 'Contact',
    menu: 'Menu',
    closeMenu: 'Close menu',
    switchLanguage: 'हिन्दी',
    switchLanguageLabel: 'Switch to Hindi',
    heroEyebrow: 'Bilingual parenting support',
    heroTitle: 'Helping Indian immigrant families thrive in Australia',
    heroIntro:
      'Practical English and Hindi video lessons for parents navigating culture, family life and children’s wellbeing.',
    explore: 'Explore learning resources',
    aboutCta: 'About C-BEEMS',
    imageLabel: 'Approved family image',
    imageHelp: 'Warm, authentic photography will replace this placeholder.',
    trustLanguage: 'English + Hindi',
    trustLessons: '8 guided lessons',
    trustSupport: 'Australia-wide support',
    resourcesTitle: 'Learning resources',
    resourcesIntro: 'Start with any lesson, then continue at your own pace.',
    exploreMore: 'Explore more',
    lesson: 'Lesson',
    videoLesson: 'English video',
    videoPlaceholder: 'Video connection will be tested in the Firebase prototype step.',
    mediaStatus: '16:9 media placeholder · only the selected language is rendered',
    emulatorLoading: 'Connecting to the local Firebase emulators…',
    emulatorConnected: 'Local Firestore connected',
    emulatorError: 'Firestore emulator is unavailable. Static prototype content is shown.',
    retry: 'Retry',
    videoLoading: 'Loading the selected-language video from Storage Emulator…',
    videoError: 'The Storage Emulator video could not be loaded.',
    backToResources: 'Back to resources',
    previous: 'Previous lesson',
    next: 'Next lesson',
    supportTitle: 'Need urgent support?',
    supportText:
      'C-BEEMS is not an emergency service. Verified Australia-wide support information will be added before production.',
    getHelp: 'Get help',
    aboutTitle: 'About C-BEEMS',
    aboutText:
      'Project background, team, partner and funder information is reserved until the content is confirmed.',
    reservedLabel: 'Reserved content',
    contactTitle: 'Contact and get help',
    contactText:
      'The contact form is reserved until its recipient, response time, retention period and privacy handling are confirmed.',
    formName: 'Name',
    formEmail: 'Email',
    formMessage: 'Message',
    formSubmit: 'Send message',
    formDisabled: 'Submission is disabled in this technical prototype.',
    privacyTitle: 'Privacy policy',
    privacyText:
      'Final policy content will describe the implemented Firebase, analytics, language preference, media and contact behaviour.',
    accessibilityTitle: 'Accessibility statement',
    accessibilityText:
      'The implementation targets WCAG 2.2 AA. The final statement will document tested measures and any remaining exceptions.',
    cookiePreferences: 'Cookie preferences',
    cookieTitle: 'Your privacy choices',
    cookieText: 'Choose whether optional analytics may be used. Lesson access is always available.',
    acceptAll: 'Accept all',
    rejectOptional: 'Reject optional',
    manage: 'Manage',
    essential: 'Essential — always active',
    analytics: 'Analytics',
    saveChoices: 'Save choices',
    footerStatus: 'Contact details awaiting confirmation',
    prototype: 'Technical prototype — no live Firebase connection',
    notFoundTitle: 'Page not found',
    notFoundText: 'The page may have moved, or the link is not part of this prototype.',
    returnHome: 'Return home',
    skipToContent: 'Skip to content',
    breadcrumbHome: 'Home',
  },
  hi: {
    brandSub: 'पालन-पोषण सहायता',
    navHome: 'मुखपृष्ठ',
    navResources: 'सीखने के संसाधन',
    navAbout: 'हमारे बारे में',
    navContact: 'संपर्क',
    menu: 'मेनू',
    closeMenu: 'मेनू बंद करें',
    switchLanguage: 'English',
    switchLanguageLabel: 'Switch to English',
    heroEyebrow: 'द्विभाषी पालन-पोषण सहायता',
    heroTitle: 'ऑस्ट्रेलिया में भारतीय प्रवासी परिवारों के लिए सहायता',
    heroIntro:
      'संस्कृति, पारिवारिक जीवन और बच्चों के कल्याण के लिए अंग्रेज़ी और हिन्दी वीडियो पाठ।',
    explore: 'सीखने के संसाधन देखें',
    aboutCta: 'C-BEEMS के बारे में',
    imageLabel: 'स्वीकृत पारिवारिक चित्र',
    imageHelp: 'यहाँ बाद में प्रामाणिक और आत्मीय तस्वीर जोड़ी जाएगी।',
    trustLanguage: 'अंग्रेज़ी + हिन्दी',
    trustLessons: '8 मार्गदर्शित पाठ',
    trustSupport: 'ऑस्ट्रेलिया-व्यापी सहायता',
    resourcesTitle: 'सीखने के संसाधन',
    resourcesIntro: 'किसी भी पाठ से शुरू करें और अपनी गति से आगे बढ़ें।',
    exploreMore: 'और देखें',
    lesson: 'पाठ',
    videoLesson: 'हिन्दी वीडियो',
    videoPlaceholder: 'Firebase प्रोटोटाइप चरण में वीडियो कनेक्शन का परीक्षण किया जाएगा।',
    mediaStatus: '16:9 मीडिया प्लेसहोल्डर · केवल चुनी हुई भाषा दिखाई जाती है',
    emulatorLoading: 'स्थानीय Firebase एमुलेटर से कनेक्ट किया जा रहा है…',
    emulatorConnected: 'स्थानीय Firestore कनेक्ट है',
    emulatorError: 'Firestore एमुलेटर उपलब्ध नहीं है। स्थिर प्रोटोटाइप सामग्री दिखाई जा रही है।',
    retry: 'फिर प्रयास करें',
    videoLoading: 'Storage Emulator से चुनी हुई भाषा का वीडियो लोड हो रहा है…',
    videoError: 'Storage Emulator का वीडियो लोड नहीं हो सका।',
    backToResources: 'संसाधनों पर वापस जाएँ',
    previous: 'पिछला पाठ',
    next: 'अगला पाठ',
    supportTitle: 'तत्काल सहायता चाहिए?',
    supportText:
      'C-BEEMS आपात सेवा नहीं है। सत्यापित ऑस्ट्रेलिया-व्यापी सहायता जानकारी प्रकाशन से पहले जोड़ी जाएगी।',
    getHelp: 'सहायता प्राप्त करें',
    aboutTitle: 'C-BEEMS के बारे में',
    aboutText:
      'परियोजना, टीम, भागीदार और वित्तपोषक की जानकारी की पुष्टि होने तक यह स्थान आरक्षित है।',
    reservedLabel: 'आरक्षित सामग्री',
    contactTitle: 'संपर्क और सहायता',
    contactText:
      'प्राप्तकर्ता, उत्तर समय, संग्रह अवधि और गोपनीयता व्यवस्था तय होने तक संपर्क फ़ॉर्म आरक्षित है।',
    formName: 'नाम',
    formEmail: 'ईमेल',
    formMessage: 'संदेश',
    formSubmit: 'संदेश भेजें',
    formDisabled: 'इस तकनीकी प्रोटोटाइप में भेजना बंद है।',
    privacyTitle: 'गोपनीयता नीति',
    privacyText:
      'अंतिम नीति Firebase, एनालिटिक्स, भाषा पसंद, मीडिया और संपर्क के वास्तविक व्यवहार का वर्णन करेगी।',
    accessibilityTitle: 'सुलभता वक्तव्य',
    accessibilityText:
      'कार्यान्वयन का लक्ष्य WCAG 2.2 AA है। अंतिम वक्तव्य परीक्षण और शेष अपवादों का विवरण देगा।',
    cookiePreferences: 'कुकी प्राथमिकताएँ',
    cookieTitle: 'आपकी गोपनीयता पसंद',
    cookieText: 'चुनें कि वैकल्पिक एनालिटिक्स का उपयोग हो सकता है या नहीं। पाठ हमेशा उपलब्ध रहते हैं।',
    acceptAll: 'सभी स्वीकार करें',
    rejectOptional: 'वैकल्पिक अस्वीकार करें',
    manage: 'प्रबंधित करें',
    essential: 'आवश्यक — हमेशा सक्रिय',
    analytics: 'एनालिटिक्स',
    saveChoices: 'पसंद सहेजें',
    footerStatus: 'संपर्क जानकारी की पुष्टि बाकी है',
    prototype: 'तकनीकी प्रोटोटाइप — लाइव Firebase कनेक्शन नहीं',
    notFoundTitle: 'पृष्ठ नहीं मिला',
    notFoundText: 'यह पृष्ठ स्थानांतरित हो सकता है या इस प्रोटोटाइप का भाग नहीं है।',
    returnHome: 'मुखपृष्ठ पर जाएँ',
    skipToContent: 'मुख्य सामग्री पर जाएँ',
    breadcrumbHome: 'मुखपृष्ठ',
  },
} as const
